version: "3.9"
services:
  db-tenant1:
    hostname: db-tenant1
    image: postgres:14
    environment:
      - POSTGRES_JOBS=2
      - POSTGRES_DB=docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    ports:
      - "15432:5432"
  db-tenant2:
    hostname: db-tenant2
    image: postgres:14
    environment:
      - POSTGRES_JOBS=2
      - POSTGRES_DB=docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password2
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    ports:
      - "15433:5432"
